apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowmesh.fullname" . }}-config
  labels:
    {{- include "flowmesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SIGNING_KEY: {{ .Values.global.jwtSigningKey | quote }}
  IAM_DB_PASSWORD: {{ .Values.services.iam.dbPassword | quote }}
  SUPPLIER_DB_PASSWORD: {{ .Values.services.supplier.dbPassword | quote }}
  WORKFLOW_DB_PASSWORD: {{ .Values.services.workflow.dbPassword | quote }}
